apiVersion: v1
kind: Config
clusters:
  - name: authn-webhook
    cluster:
      #server: https://192.168.169.137:9444/
      server: https://192.168.169.129:32696/
      insecure-skip-tls-verify: true
users:
  - name: kube-apiserver
contexts:
- context:
    cluster: authn-webhook
    user: kube-apiserver
  name: authn-webhook
current-context: authn-webhook
