apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: authn-webhook
  name: authn-webhook
  namespace: webhook
spec:
  containers:
  - command:
    - "./main"
    - '-protocol=https'
    - '-port=8080'
    - '-cert=/go/src/pki/server.crt'
    - '-key=/go/src/pki/server.key'
    - '-secret=$(SECRET)'
    image: authentication-webhook:1.0
    name: authn-webhook
    env:
      - name: SECRET
        valueFrom:
          secretKeyRef:
            key: secret
            name: authn-secret
    resources: {}
    volumeMounts:
      - mountPath: /go/src/pki
        name: authn-cert-key
  volumes:
    - name: authn-cert-key
      configMap:
        name: authn-configmap
  dnsPolicy: ClusterFirst
   
  restartPolicy: Always
  tolerations:
    - key: kubernetes.io/worker
      effect: NoSchedule
      operator: Exists
status: {}
